// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file.proto

#include "file.pb.h"
#include "file.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace example {

static const char* Summator_method_names[] = {
  "/example.Summator/Sum",
};

std::unique_ptr< Summator::Stub> Summator::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Summator::Stub> stub(new Summator::Stub(channel));
  return stub;
}

Summator::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Sum_(Summator_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Summator::Stub::Sum(::grpc::ClientContext* context, const ::example::InputData& request, ::example::Result* response) {
  return ::grpc::internal::BlockingUnaryCall< ::example::InputData, ::example::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sum_, context, request, response);
}

void Summator::Stub::experimental_async::Sum(::grpc::ClientContext* context, const ::example::InputData* request, ::example::Result* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::example::InputData, ::example::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sum_, context, request, response, std::move(f));
}

void Summator::Stub::experimental_async::Sum(::grpc::ClientContext* context, const ::example::InputData* request, ::example::Result* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::example::Result>* Summator::Stub::PrepareAsyncSumRaw(::grpc::ClientContext* context, const ::example::InputData& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::example::Result, ::example::InputData, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::example::Result>* Summator::Stub::AsyncSumRaw(::grpc::ClientContext* context, const ::example::InputData& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSumRaw(context, request, cq);
  result->StartCall();
  return result;
}

Summator::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Summator_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Summator::Service, ::example::InputData, ::example::Result, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Summator::Service* service,
             ::grpc::ServerContext* ctx,
             const ::example::InputData* req,
             ::example::Result* resp) {
               return service->Sum(ctx, req, resp);
             }, this)));
}

Summator::Service::~Service() {
}

::grpc::Status Summator::Service::Sum(::grpc::ServerContext* context, const ::example::InputData* request, ::example::Result* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace example

